Responsive Desktop Website
Kwaku28/My-Portfolio pull request #2
Opened 2022-12-16 19:24 UTC by Kwaku28

This is a full desktop website version
Sections added:
1. Portfolio: Indicating an introduction and worked on projects
2. About: Comprising of skills and experience with programming languages
3. Contact: Reach out form submitted to the website owner

Transitions (eg. scale) added to give a professional touch and user friendly.
Responsive to fit smaller screens.

2022-12-16 20:15 UTC, Lizdev-05 requested changes
Hi @Kwaku28, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media2.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>
## Highlights

- No linter errors ✔️
- Correct Github flow ✔️
- Descriptive PR ✔️
- Professional README file ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 20:15 UTC, Lizdev-05 commented on style.css
> +
Great job so far 👍,  kindly check the responsiveness of your frames, it is breaking. 👇
<img width="764" alt="image" src="https://user-images.githubusercontent.com/73854999/208180984-86984ee3-5d9e-4a7d-9773-7660d3ceea51.png">

2022-12-16 20:15 UTC, Lizdev-05 commented on style.css
> +
Kindly the styling of your about-section, it is currently overflowing🙂
<img width="764" alt="image" src="https://user-images.githubusercontent.com/73854999/208181403-daca2c1c-60f4-4d0b-8090-3dae2678f1f3.png">

2022-12-16 20:15 UTC, Lizdev-05 commented on style.css
> +
Great job adding the background image 👍, kindly update the styling as it is currently not responsive and also, the background image is overflowing 🙂
<img width="764" alt="image" src="https://user-images.githubusercontent.com/73854999/208181740-0a113ac3-4926-472b-9a3c-b11a9d462091.png">

2022-12-17 13:18 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @Kwaku28 , 

I am Favour 👩🏽 , your reviewer for this Pull Request.

Great Job implementing all the required changes suggested by the previous code reviewer. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Great design/UI ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-17 17:52 UTC, merged